version: '3.9'

services:
  worker:
    image: coldbolt/productsbolt-worker:latest
    env_file:
      - .worker.env
    networks:
      - productsbolt_net
    deploy:
      mode: global
      restart_policy:
        condition: any

  headful-worker:
    image: coldbolt/productsbolt-worker:latest
    env_file:
      - .worker.headful.env
    networks:
      - productsbolt_net
    deploy:
      mode: global
      restart_policy:
        condition: any

networks:
  productsbolt_net:
    driver: overlay
